"""empty message

Revision ID: 941a23c9314a
Revises: 38309123ccfc
Create Date: 2025-03-13 17:32:52.248665

"""

from alembic import op
import sqlalchemy as sa
from fastapi_storages.integrations.sqlalchemy import ImageType


# revision identifiers, used by Alembic.
revision = '941a23c9314a'
down_revision = '38309123ccfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'confirmation_url', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'confirmation_url', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
